#include "analisador_sintatico.hpp"

vector<pair<t_nont,int>> vec_rules = vector<pair<t_nont,int>>();
vector<unordered_map<int,int>> actionTable = vector<unordered_map<int,int>>(MAX_ACTION_TABLE_SIZE);
stack<int> states = stack<int>();

//The rules vector stores the non-terminal to the left of the rule and the length of the rule
void build_rule_vector(){
	vec_rules.push_back(make_pair(P,1));
	vec_rules.push_back(make_pair(LDE,2));
	vec_rules.push_back(make_pair(LDE,1));
	vec_rules.push_back(make_pair(DE,1));
	vec_rules.push_back(make_pair(DE,1));
	vec_rules.push_back(make_pair(T,1));
	vec_rules.push_back(make_pair(T,1));
	vec_rules.push_back(make_pair(T,1));
	vec_rules.push_back(make_pair(T,1));
	vec_rules.push_back(make_pair(T,1));
	vec_rules.push_back(make_pair(DT,9));
	vec_rules.push_back(make_pair(DT,8));
	vec_rules.push_back(make_pair(DT,4));
	vec_rules.push_back(make_pair(DC,5));
	vec_rules.push_back(make_pair(DC,3));
	vec_rules.push_back(make_pair(DF,10));
	vec_rules.push_back(make_pair(LP,5));
	vec_rules.push_back(make_pair(LP,3));
	vec_rules.push_back(make_pair(LP,0));
	vec_rules.push_back(make_pair(B,4));
	vec_rules.push_back(make_pair(LDV,2));
	vec_rules.push_back(make_pair(LDV,1));
	vec_rules.push_back(make_pair(LDV,0));
	vec_rules.push_back(make_pair(LS,2));
	vec_rules.push_back(make_pair(LS,1));
	vec_rules.push_back(make_pair(DV,5));
	vec_rules.push_back(make_pair(LI,3));
	vec_rules.push_back(make_pair(LI,1));
	vec_rules.push_back(make_pair(S,6));
	vec_rules.push_back(make_pair(S,9));
	vec_rules.push_back(make_pair(S,7));
	vec_rules.push_back(make_pair(S,8));
	vec_rules.push_back(make_pair(S,2));
	vec_rules.push_back(make_pair(S,5));
	vec_rules.push_back(make_pair(S,2));
	vec_rules.push_back(make_pair(S,2));
	vec_rules.push_back(make_pair(S,3));
	vec_rules.push_back(make_pair(E,3));
	vec_rules.push_back(make_pair(E,3));
	vec_rules.push_back(make_pair(E,1));
	vec_rules.push_back(make_pair(L,3));
	vec_rules.push_back(make_pair(L,3));
	vec_rules.push_back(make_pair(L,3));
	vec_rules.push_back(make_pair(L,3));
	vec_rules.push_back(make_pair(L,3));
	vec_rules.push_back(make_pair(L,3));
	vec_rules.push_back(make_pair(L,1));
	vec_rules.push_back(make_pair(R,3));
	vec_rules.push_back(make_pair(R,3));
	vec_rules.push_back(make_pair(R,1));
	vec_rules.push_back(make_pair(Y,3));
	vec_rules.push_back(make_pair(Y,3));
	vec_rules.push_back(make_pair(Y,1));
	vec_rules.push_back(make_pair(F,1));
	vec_rules.push_back(make_pair(F,2));
	vec_rules.push_back(make_pair(F,2));
	vec_rules.push_back(make_pair(F,2));
	vec_rules.push_back(make_pair(F,2));
	vec_rules.push_back(make_pair(F,3));
	vec_rules.push_back(make_pair(F,5));
	vec_rules.push_back(make_pair(F,2));
	vec_rules.push_back(make_pair(F,2));
	vec_rules.push_back(make_pair(F,1));
	vec_rules.push_back(make_pair(F,1));
	vec_rules.push_back(make_pair(F,1));
	vec_rules.push_back(make_pair(F,1));
	vec_rules.push_back(make_pair(F,1));
	vec_rules.push_back(make_pair(LE,3));
	vec_rules.push_back(make_pair(LE,1));
	vec_rules.push_back(make_pair(LE,0));
	vec_rules.push_back(make_pair(LV,3));
	vec_rules.push_back(make_pair(LV,4));
	vec_rules.push_back(make_pair(LV,1));
	vec_rules.push_back(make_pair(TRU,1));
	vec_rules.push_back(make_pair(FALS,1));
	vec_rules.push_back(make_pair(CH,1));
	vec_rules.push_back(make_pair(ST,1));
	vec_rules.push_back(make_pair(NU,1));
	vec_rules.push_back(make_pair(IDT,1));
	vec_rules.push_back(make_pair(IDU,1));
	vec_rules.push_back(make_pair(IDD,1));
	vec_rules.push_back(make_pair(NB,0));
	vec_rules.push_back(make_pair(NF,0));
	vec_rules.push_back(make_pair(MA,0));
	vec_rules.push_back(make_pair(ME,0));
	vec_rules.push_back(make_pair(MC,0));
	vec_rules.push_back(make_pair(MF,0));
	vec_rules.push_back(make_pair(MT,0));
	vec_rules.push_back(make_pair(MW,0));


}

void build_action_table(){
	//Table generated by http://jsmachines.sourceforge.net/machines/lalr1.html
	//State: 0
	actionTable[0][TYPE] = 6;
	actionTable[0][FUNCTION] = 5;
	actionTable[0][LDE] = 1;
	actionTable[0][DE] = 2;
	actionTable[0][DT] = 4;
	actionTable[0][DF] = 3;

	//State: 1
	actionTable[1][TYPE] = 6;
	actionTable[1][FUNCTION] = 5;
	actionTable[1][ENDFILE] = ACC;
	actionTable[1][DE] = 7;
	actionTable[1][DT] = 4;
	actionTable[1][DF] = 3;

	//State: 2
	actionTable[2][TYPE] = -2;
	actionTable[2][FUNCTION] = -2;
	actionTable[2][ENDFILE] = -2;

	//State: 3
	actionTable[3][TYPE] = -3;
	actionTable[3][FUNCTION] = -3;
	actionTable[3][ENDFILE] = -3;

	//State: 4
	actionTable[4][TYPE] = -4;
	actionTable[4][FUNCTION] = -4;
	actionTable[4][ENDFILE] = -4;

	//State: 5
	actionTable[5][ID] = 9;
	actionTable[5][IDD] = 8;

	//State: 6
	actionTable[6][ID] = 9;
	actionTable[6][IDD] = 10;

	//State: 7
	actionTable[7][TYPE] = -1;
	actionTable[7][FUNCTION] = -1;
	actionTable[7][ENDFILE] = -1;

	//State: 8
	actionTable[8][LEFT_PARENTHESIS] = -82;
	actionTable[8][NF] = 11;

	//State: 9
	actionTable[9][TYPE] = -80;
	actionTable[9][EQUALS] = -80;
	actionTable[9][COLON] = -80;
	actionTable[9][FUNCTION] = -80;
	actionTable[9][LEFT_PARENTHESIS] = -80;
	actionTable[9][COMMA] = -80;
	actionTable[9][ENDFILE] = -80;

	//State: 10
	actionTable[10][EQUALS] = 12;

	//State: 11
	actionTable[11][LEFT_PARENTHESIS] = 13;

	//State: 12
	actionTable[12][INTEGER] = 17;
	actionTable[12][CHAR] = 18;
	actionTable[12][BOOLEAN] = 19;
	actionTable[12][STRING] = 20;
	actionTable[12][ARRAY] = 14;
	actionTable[12][STRUCT] = 15;
	actionTable[12][ID] = 22;
	actionTable[12][T] = 16;
	actionTable[12][IDU] = 21;

	//State: 13
	actionTable[13][RIGHT_PARENTHESIS] = -18;
	actionTable[13][COMMA] = -18;
	actionTable[13][ID] = 9;
	actionTable[13][LP] = 23;
	actionTable[13][IDD] = 24;

	//State: 14
	actionTable[14][LEFT_SQUARE] = 25;

	//State: 15
	actionTable[15][LEFT_BRACES] = -81;
	actionTable[15][NB] = 26;

	//State: 16
	actionTable[16][TYPE] = -12;
	actionTable[16][FUNCTION] = -12;
	actionTable[16][ENDFILE] = -12;

	//State: 17
	actionTable[17][TYPE] = -5;
	actionTable[17][LEFT_BRACES] = -5;
	actionTable[17][RIGHT_BRACES] = -5;
	actionTable[17][SEMI_COLON] = -5;
	actionTable[17][FUNCTION] = -5;
	actionTable[17][RIGHT_PARENTHESIS] = -5;
	actionTable[17][COMMA] = -5;
	actionTable[17][ENDFILE] = -5;

	//State: 18
	actionTable[18][TYPE] = -6;
	actionTable[18][LEFT_BRACES] = -6;
	actionTable[18][RIGHT_BRACES] = -6;
	actionTable[18][SEMI_COLON] = -6;
	actionTable[18][FUNCTION] = -6;
	actionTable[18][RIGHT_PARENTHESIS] = -6;
	actionTable[18][COMMA] = -6;
	actionTable[18][ENDFILE] = -6;

	//State: 19
	actionTable[19][TYPE] = -7;
	actionTable[19][LEFT_BRACES] = -7;
	actionTable[19][RIGHT_BRACES] = -7;
	actionTable[19][SEMI_COLON] = -7;
	actionTable[19][FUNCTION] = -7;
	actionTable[19][RIGHT_PARENTHESIS] = -7;
	actionTable[19][COMMA] = -7;
	actionTable[19][ENDFILE] = -7;

	//State: 20
	actionTable[20][TYPE] = -8;
	actionTable[20][LEFT_BRACES] = -8;
	actionTable[20][RIGHT_BRACES] = -8;
	actionTable[20][SEMI_COLON] = -8;
	actionTable[20][FUNCTION] = -8;
	actionTable[20][RIGHT_PARENTHESIS] = -8;
	actionTable[20][COMMA] = -8;
	actionTable[20][ENDFILE] = -8;

	//State: 21
	actionTable[21][TYPE] = -9;
	actionTable[21][LEFT_BRACES] = -9;
	actionTable[21][RIGHT_BRACES] = -9;
	actionTable[21][SEMI_COLON] = -9;
	actionTable[21][FUNCTION] = -9;
	actionTable[21][RIGHT_PARENTHESIS] = -9;
	actionTable[21][COMMA] = -9;
	actionTable[21][ENDFILE] = -9;

	//State: 22
	actionTable[22][TYPE] = -79;
	actionTable[22][EQUALS] = -79;
	actionTable[22][LEFT_SQUARE] = -79;
	actionTable[22][RIGHT_SQUARE] = -79;
	actionTable[22][LEFT_BRACES] = -79;
	actionTable[22][RIGHT_BRACES] = -79;
	actionTable[22][SEMI_COLON] = -79;
	actionTable[22][FUNCTION] = -79;
	actionTable[22][LEFT_PARENTHESIS] = -79;
	actionTable[22][RIGHT_PARENTHESIS] = -79;
	actionTable[22][COMMA] = -79;
	actionTable[22][IF] = -79;
	actionTable[22][ELSE] = -79;
	actionTable[22][WHILE] = -79;
	actionTable[22][DO] = -79;
	actionTable[22][BREAK] = -79;
	actionTable[22][CONTINUE] = -79;
	actionTable[22][RETURN] = -79;
	actionTable[22][AND] = -79;
	actionTable[22][OR] = -79;
	actionTable[22][LESS_THAN] = -79;
	actionTable[22][GREATER_THAN] = -79;
	actionTable[22][LESS_OR_EQUAL] = -79;
	actionTable[22][GREATER_OR_EQUAL] = -79;
	actionTable[22][EQUAL_EQUAL] = -79;
	actionTable[22][NOT_EQUAL] = -79;
	actionTable[22][PLUS] = -79;
	actionTable[22][MINUS] = -79;
	actionTable[22][TIMES] = -79;
	actionTable[22][DIVIDE] = -79;
	actionTable[22][PLUS_PLUS] = -79;
	actionTable[22][MINUS_MINUS] = -79;
	actionTable[22][DOT] = -79;
	actionTable[22][ID] = -79;
	actionTable[22][ENDFILE] = -79;

	//State: 23
	actionTable[23][RIGHT_PARENTHESIS] = 27;
	actionTable[23][COMMA] = 28;

	//State: 24
	actionTable[24][COLON] = 29;

	//State: 25
	actionTable[25][NUMERAL] = 31;
	actionTable[25][NU] = 30;

	//State: 26
	actionTable[26][LEFT_BRACES] = 32;

	//State: 27
	actionTable[27][COLON] = 33;

	//State: 28
	actionTable[28][ID] = 9;
	actionTable[28][IDD] = 34;

	//State: 29
	actionTable[29][INTEGER] = 17;
	actionTable[29][CHAR] = 18;
	actionTable[29][BOOLEAN] = 19;
	actionTable[29][STRING] = 20;
	actionTable[29][ID] = 22;
	actionTable[29][T] = 35;
	actionTable[29][IDU] = 21;

	//State: 30
	actionTable[30][RIGHT_SQUARE] = 36;

	//State: 31
	actionTable[31][RIGHT_SQUARE] = -77;
	actionTable[31][SEMI_COLON] = -77;
	actionTable[31][RIGHT_PARENTHESIS] = -77;
	actionTable[31][COMMA] = -77;
	actionTable[31][AND] = -77;
	actionTable[31][OR] = -77;
	actionTable[31][LESS_THAN] = -77;
	actionTable[31][GREATER_THAN] = -77;
	actionTable[31][LESS_OR_EQUAL] = -77;
	actionTable[31][GREATER_OR_EQUAL] = -77;
	actionTable[31][EQUAL_EQUAL] = -77;
	actionTable[31][NOT_EQUAL] = -77;
	actionTable[31][PLUS] = -77;
	actionTable[31][MINUS] = -77;
	actionTable[31][TIMES] = -77;
	actionTable[31][DIVIDE] = -77;

	//State: 32
	actionTable[32][ID] = 9;
	actionTable[32][DC] = 37;
	actionTable[32][LI] = 38;
	actionTable[32][IDD] = 39;

	//State: 33
	actionTable[33][INTEGER] = 17;
	actionTable[33][CHAR] = 18;
	actionTable[33][BOOLEAN] = 19;
	actionTable[33][STRING] = 20;
	actionTable[33][ID] = 22;
	actionTable[33][T] = 40;
	actionTable[33][IDU] = 21;

	//State: 34
	actionTable[34][COLON] = 41;

	//State: 35
	actionTable[35][RIGHT_PARENTHESIS] = -17;
	actionTable[35][COMMA] = -17;

	//State: 36
	actionTable[36][OF] = 42;

	//State: 37
	actionTable[37][RIGHT_BRACES] = 43;
	actionTable[37][SEMI_COLON] = 44;

	//State: 38
	actionTable[38][COLON] = 45;
	actionTable[38][COMMA] = 46;

	//State: 39
	actionTable[39][COLON] = -27;
	actionTable[39][COMMA] = -27;

	//State: 40
	actionTable[40][LEFT_BRACES] = -86;
	actionTable[40][MF] = 47;

	//State: 41
	actionTable[41][INTEGER] = 17;
	actionTable[41][CHAR] = 18;
	actionTable[41][BOOLEAN] = 19;
	actionTable[41][STRING] = 20;
	actionTable[41][ID] = 22;
	actionTable[41][T] = 48;
	actionTable[41][IDU] = 21;

	//State: 42
	actionTable[42][INTEGER] = 17;
	actionTable[42][CHAR] = 18;
	actionTable[42][BOOLEAN] = 19;
	actionTable[42][STRING] = 20;
	actionTable[42][ID] = 22;
	actionTable[42][T] = 49;
	actionTable[42][IDU] = 21;

	//State: 43
	actionTable[43][TYPE] = -11;
	actionTable[43][FUNCTION] = -11;
	actionTable[43][ENDFILE] = -11;

	//State: 44
	actionTable[44][ID] = 9;
	actionTable[44][LI] = 50;
	actionTable[44][IDD] = 39;

	//State: 45
	actionTable[45][INTEGER] = 17;
	actionTable[45][CHAR] = 18;
	actionTable[45][BOOLEAN] = 19;
	actionTable[45][STRING] = 20;
	actionTable[45][ID] = 22;
	actionTable[45][T] = 51;
	actionTable[45][IDU] = 21;

	//State: 46
	actionTable[46][ID] = 9;
	actionTable[46][IDD] = 52;

	//State: 47
	actionTable[47][LEFT_BRACES] = 54;
	actionTable[47][B] = 53;

	//State: 48
	actionTable[48][RIGHT_PARENTHESIS] = -16;
	actionTable[48][COMMA] = -16;

	//State: 49
	actionTable[49][TYPE] = -10;
	actionTable[49][FUNCTION] = -10;
	actionTable[49][ENDFILE] = -10;

	//State: 50
	actionTable[50][COLON] = 55;
	actionTable[50][COMMA] = 46;

	//State: 51
	actionTable[51][RIGHT_BRACES] = -14;
	actionTable[51][SEMI_COLON] = -14;

	//State: 52
	actionTable[52][COLON] = -26;
	actionTable[52][COMMA] = -26;

	//State: 53
	actionTable[53][TYPE] = -15;
	actionTable[53][FUNCTION] = -15;
	actionTable[53][ENDFILE] = -15;

	//State: 54
	actionTable[54][TYPE] = -22;
	actionTable[54][LEFT_BRACES] = -22;
	actionTable[54][RIGHT_BRACES] = -22;
	actionTable[54][FUNCTION] = -22;
	actionTable[54][VAR] = -22;
	actionTable[54][IF] = -22;
	actionTable[54][ELSE] = -22;
	actionTable[54][WHILE] = -22;
	actionTable[54][DO] = -22;
	actionTable[54][BREAK] = -22;
	actionTable[54][CONTINUE] = -22;
	actionTable[54][RETURN] = -22;
	actionTable[54][ID] = -22;
	actionTable[54][ENDFILE] = -22;
	actionTable[54][LDV] = 56;
	actionTable[54][DV] = 57;

	//State: 55
	actionTable[55][INTEGER] = 17;
	actionTable[55][CHAR] = 18;
	actionTable[55][BOOLEAN] = 19;
	actionTable[55][STRING] = 20;
	actionTable[55][ID] = 22;
	actionTable[55][T] = 59;
	actionTable[55][IDU] = 21;

	//State: 56
	actionTable[56][LEFT_BRACES] = -81;
	actionTable[56][VAR] = 58;
	actionTable[56][IF] = 63;
	actionTable[56][WHILE] = 64;
	actionTable[56][DO] = 65;
	actionTable[56][BREAK] = 68;
	actionTable[56][CONTINUE] = 69;
	actionTable[56][RETURN] = 70;
	actionTable[56][ID] = 22;
	actionTable[56][LS] = 60;
	actionTable[56][DV] = 61;
	actionTable[56][S] = 62;
	actionTable[56][LV] = 67;
	actionTable[56][IDU] = 71;
	actionTable[56][NB] = 66;

	//State: 57
	actionTable[57][TYPE] = -21;
	actionTable[57][LEFT_BRACES] = -21;
	actionTable[57][RIGHT_BRACES] = -21;
	actionTable[57][FUNCTION] = -21;
	actionTable[57][VAR] = -21;
	actionTable[57][IF] = -21;
	actionTable[57][ELSE] = -21;
	actionTable[57][WHILE] = -21;
	actionTable[57][DO] = -21;
	actionTable[57][BREAK] = -21;
	actionTable[57][CONTINUE] = -21;
	actionTable[57][RETURN] = -21;
	actionTable[57][ID] = -21;
	actionTable[57][ENDFILE] = -21;

	//State: 58
	actionTable[58][ID] = 9;
	actionTable[58][LI] = 72;
	actionTable[58][IDD] = 39;

	//State: 59
	actionTable[59][RIGHT_BRACES] = -13;
	actionTable[59][SEMI_COLON] = -13;

	//State: 60
	actionTable[60][LEFT_BRACES] = -81;
	actionTable[60][RIGHT_BRACES] = 73;
	actionTable[60][IF] = 63;
	actionTable[60][WHILE] = 64;
	actionTable[60][DO] = 65;
	actionTable[60][BREAK] = 68;
	actionTable[60][CONTINUE] = 69;
	actionTable[60][RETURN] = 70;
	actionTable[60][ID] = 22;
	actionTable[60][S] = 74;
	actionTable[60][LV] = 67;
	actionTable[60][IDU] = 71;
	actionTable[60][NB] = 66;

	//State: 61
	actionTable[61][TYPE] = -20;
	actionTable[61][LEFT_BRACES] = -20;
	actionTable[61][RIGHT_BRACES] = -20;
	actionTable[61][FUNCTION] = -20;
	actionTable[61][VAR] = -20;
	actionTable[61][IF] = -20;
	actionTable[61][ELSE] = -20;
	actionTable[61][WHILE] = -20;
	actionTable[61][DO] = -20;
	actionTable[61][BREAK] = -20;
	actionTable[61][CONTINUE] = -20;
	actionTable[61][RETURN] = -20;
	actionTable[61][ID] = -20;
	actionTable[61][ENDFILE] = -20;

	//State: 62
	actionTable[62][LEFT_BRACES] = -24;
	actionTable[62][RIGHT_BRACES] = -24;
	actionTable[62][IF] = -24;
	actionTable[62][WHILE] = -24;
	actionTable[62][DO] = -24;
	actionTable[62][BREAK] = -24;
	actionTable[62][CONTINUE] = -24;
	actionTable[62][RETURN] = -24;
	actionTable[62][ID] = -24;

	//State: 63
	actionTable[63][LEFT_PARENTHESIS] = 75;

	//State: 64
	actionTable[64][LEFT_PARENTHESIS] = -88;
	actionTable[64][MW
	] = 76
	;

	//State: 65
	actionTable[65][LEFT_BRACES] = -88;
	actionTable[65][RIGHT_BRACES] = -88;
	actionTable[65][IF] = -88;
	actionTable[65][ELSE] = -88;
	actionTable[65][WHILE] = -88;
	actionTable[65][DO] = -88;
	actionTable[65][BREAK] = -88;
	actionTable[65][CONTINUE] = -88;
	actionTable[65][RETURN] = -88;
	actionTable[65][ID] = -88;
	actionTable[65][MW
	] = 77
	;

	//State: 66
	actionTable[66][LEFT_BRACES] = 54;
	actionTable[66][B] = 78;

	//State: 67
	actionTable[67][EQUALS] = -83;
	actionTable[67][LEFT_SQUARE] = 81;
	actionTable[67][DOT] = 80;
	actionTable[67][MA] = 79;

	//State: 68
	actionTable[68][SEMI_COLON] = 82;

	//State: 69
	actionTable[69][SEMI_COLON] = 83;

	//State: 70
	actionTable[70][LEFT_PARENTHESIS] = 92;
	actionTable[70][MINUS] = 94;
	actionTable[70][PLUS_PLUS] = 90;
	actionTable[70][MINUS_MINUS] = 91;
	actionTable[70][NOT] = 95;
	actionTable[70][TRUE] = 101;
	actionTable[70][FALSE] = 102;
	actionTable[70][CHARACTER] = 103;
	actionTable[70][STRINGVAL] = 104;
	actionTable[70][NUMERAL] = 31;
	actionTable[70][ID] = 22;
	actionTable[70][E] = 84;
	actionTable[70][L] = 85;
	actionTable[70][R] = 86;
	actionTable[70][Y] = 87;
	actionTable[70][F] = 88;
	actionTable[70][LV] = 89;
	actionTable[70][TRU] = 96;
	actionTable[70][FALS] = 97;
	actionTable[70][CH] = 98;
	actionTable[70][ST] = 99;
	actionTable[70][NU] = 100;
	actionTable[70][IDU] = 93;

	//State: 71
	actionTable[71][EQUALS] = -72;
	actionTable[71][LEFT_SQUARE] = -72;
	actionTable[71][RIGHT_SQUARE] = -72;
	actionTable[71][LEFT_BRACES] = -72;
	actionTable[71][RIGHT_BRACES] = -72;
	actionTable[71][SEMI_COLON] = -72;
	actionTable[71][RIGHT_PARENTHESIS] = -72;
	actionTable[71][COMMA] = -72;
	actionTable[71][IF] = -72;
	actionTable[71][ELSE] = -72;
	actionTable[71][WHILE] = -72;
	actionTable[71][DO] = -72;
	actionTable[71][BREAK] = -72;
	actionTable[71][CONTINUE] = -72;
	actionTable[71][RETURN] = -72;
	actionTable[71][AND] = -72;
	actionTable[71][OR] = -72;
	actionTable[71][LESS_THAN] = -72;
	actionTable[71][GREATER_THAN] = -72;
	actionTable[71][LESS_OR_EQUAL] = -72;
	actionTable[71][GREATER_OR_EQUAL] = -72;
	actionTable[71][EQUAL_EQUAL] = -72;
	actionTable[71][NOT_EQUAL] = -72;
	actionTable[71][PLUS] = -72;
	actionTable[71][MINUS] = -72;
	actionTable[71][TIMES] = -72;
	actionTable[71][DIVIDE] = -72;
	actionTable[71][DOT] = -72;
	actionTable[71][ID] = -72;

	//State: 72
	actionTable[72][COLON] = 105;
	actionTable[72][COMMA] = 46;

	//State: 73
	actionTable[73][TYPE] = -19;
	actionTable[73][LEFT_BRACES] = -19;
	actionTable[73][RIGHT_BRACES] = -19;
	actionTable[73][FUNCTION] = -19;
	actionTable[73][IF] = -19;
	actionTable[73][ELSE] = -19;
	actionTable[73][WHILE] = -19;
	actionTable[73][DO] = -19;
	actionTable[73][BREAK] = -19;
	actionTable[73][CONTINUE] = -19;
	actionTable[73][RETURN] = -19;
	actionTable[73][ID] = -19;
	actionTable[73][ENDFILE] = -19;

	//State: 74
	actionTable[74][LEFT_BRACES] = -23;
	actionTable[74][RIGHT_BRACES] = -23;
	actionTable[74][IF] = -23;
	actionTable[74][WHILE] = -23;
	actionTable[74][DO] = -23;
	actionTable[74][BREAK] = -23;
	actionTable[74][CONTINUE] = -23;
	actionTable[74][RETURN] = -23;
	actionTable[74][ID] = -23;

	//State: 75
	actionTable[75][LEFT_PARENTHESIS] = 92;
	actionTable[75][MINUS] = 94;
	actionTable[75][PLUS_PLUS] = 90;
	actionTable[75][MINUS_MINUS] = 91;
	actionTable[75][NOT] = 95;
	actionTable[75][TRUE] = 101;
	actionTable[75][FALSE] = 102;
	actionTable[75][CHARACTER] = 103;
	actionTable[75][STRINGVAL] = 104;
	actionTable[75][NUMERAL] = 31;
	actionTable[75][ID] = 22;
	actionTable[75][E] = 106;
	actionTable[75][L] = 85;
	actionTable[75][R] = 86;
	actionTable[75][Y] = 87;
	actionTable[75][F] = 88;
	actionTable[75][LV] = 89;
	actionTable[75][TRU] = 96;
	actionTable[75][FALS] = 97;
	actionTable[75][CH] = 98;
	actionTable[75][ST] = 99;
	actionTable[75][NU] = 100;
	actionTable[75][IDU] = 93;

	//State: 76
	actionTable[76][LEFT_PARENTHESIS] = 107;

	//State: 77
	actionTable[77][LEFT_BRACES] = -81;
	actionTable[77][IF] = 63;
	actionTable[77][WHILE] = 64;
	actionTable[77][DO] = 65;
	actionTable[77][BREAK] = 68;
	actionTable[77][CONTINUE] = 69;
	actionTable[77][RETURN] = 70;
	actionTable[77][ID] = 22;
	actionTable[77][S] = 108;
	actionTable[77][LV] = 67;
	actionTable[77][IDU] = 71;
	actionTable[77][NB] = 66;

	//State: 78
	actionTable[78][LEFT_BRACES] = -32;
	actionTable[78][RIGHT_BRACES] = -32;
	actionTable[78][IF] = -32;
	actionTable[78][ELSE] = -32;
	actionTable[78][WHILE] = -32;
	actionTable[78][DO] = -32;
	actionTable[78][BREAK] = -32;
	actionTable[78][CONTINUE] = -32;
	actionTable[78][RETURN] = -32;
	actionTable[78][ID] = -32;

	//State: 79
	actionTable[79][EQUALS] = 109;

	//State: 80
	actionTable[80][ID] = 111;
	actionTable[80][IDT] = 110;

	//State: 81
	actionTable[81][LEFT_PARENTHESIS] = 92;
	actionTable[81][MINUS] = 94;
	actionTable[81][PLUS_PLUS] = 90;
	actionTable[81][MINUS_MINUS] = 91;
	actionTable[81][NOT] = 95;
	actionTable[81][TRUE] = 101;
	actionTable[81][FALSE] = 102;
	actionTable[81][CHARACTER] = 103;
	actionTable[81][STRINGVAL] = 104;
	actionTable[81][NUMERAL] = 31;
	actionTable[81][ID] = 22;
	actionTable[81][E] = 112;
	actionTable[81][L] = 85;
	actionTable[81][R] = 86;
	actionTable[81][Y] = 87;
	actionTable[81][F] = 88;
	actionTable[81][LV] = 89;
	actionTable[81][TRU] = 96;
	actionTable[81][FALS] = 97;
	actionTable[81][CH] = 98;
	actionTable[81][ST] = 99;
	actionTable[81][NU] = 100;
	actionTable[81][IDU] = 93;

	//State: 82
	actionTable[82][LEFT_BRACES] = -34;
	actionTable[82][RIGHT_BRACES] = -34;
	actionTable[82][IF] = -34;
	actionTable[82][ELSE] = -34;
	actionTable[82][WHILE] = -34;
	actionTable[82][DO] = -34;
	actionTable[82][BREAK] = -34;
	actionTable[82][CONTINUE] = -34;
	actionTable[82][RETURN] = -34;
	actionTable[82][ID] = -34;

	//State: 83
	actionTable[83][LEFT_BRACES] = -35;
	actionTable[83][RIGHT_BRACES] = -35;
	actionTable[83][IF] = -35;
	actionTable[83][ELSE] = -35;
	actionTable[83][WHILE] = -35;
	actionTable[83][DO] = -35;
	actionTable[83][BREAK] = -35;
	actionTable[83][CONTINUE] = -35;
	actionTable[83][RETURN] = -35;
	actionTable[83][ID] = -35;

	//State: 84
	actionTable[84][SEMI_COLON] = 113;
	actionTable[84][AND] = 114;
	actionTable[84][OR] = 115;

	//State: 85
	actionTable[85][RIGHT_SQUARE] = -39;
	actionTable[85][SEMI_COLON] = -39;
	actionTable[85][RIGHT_PARENTHESIS] = -39;
	actionTable[85][COMMA] = -39;
	actionTable[85][AND] = -39;
	actionTable[85][OR] = -39;
	actionTable[85][LESS_THAN] = 116;
	actionTable[85][GREATER_THAN] = 117;
	actionTable[85][LESS_OR_EQUAL] = 118;
	actionTable[85][GREATER_OR_EQUAL] = 119;
	actionTable[85][EQUAL_EQUAL] = 120;
	actionTable[85][NOT_EQUAL] = 121;

	//State: 86
	actionTable[86][RIGHT_SQUARE] = -46;
	actionTable[86][SEMI_COLON] = -46;
	actionTable[86][RIGHT_PARENTHESIS] = -46;
	actionTable[86][COMMA] = -46;
	actionTable[86][AND] = -46;
	actionTable[86][OR] = -46;
	actionTable[86][LESS_THAN] = -46;
	actionTable[86][GREATER_THAN] = -46;
	actionTable[86][LESS_OR_EQUAL] = -46;
	actionTable[86][GREATER_OR_EQUAL] = -46;
	actionTable[86][EQUAL_EQUAL] = -46;
	actionTable[86][NOT_EQUAL] = -46;
	actionTable[86][PLUS] = 122;
	actionTable[86][MINUS] = 123;

	//State: 87
	actionTable[87][RIGHT_SQUARE] = -49;
	actionTable[87][SEMI_COLON] = -49;
	actionTable[87][RIGHT_PARENTHESIS] = -49;
	actionTable[87][COMMA] = -49;
	actionTable[87][AND] = -49;
	actionTable[87][OR] = -49;
	actionTable[87][LESS_THAN] = -49;
	actionTable[87][GREATER_THAN] = -49;
	actionTable[87][LESS_OR_EQUAL] = -49;
	actionTable[87][GREATER_OR_EQUAL] = -49;
	actionTable[87][EQUAL_EQUAL] = -49;
	actionTable[87][NOT_EQUAL] = -49;
	actionTable[87][PLUS] = -49;
	actionTable[87][MINUS] = -49;
	actionTable[87][TIMES] = 124;
	actionTable[87][DIVIDE] = 125;

	//State: 88
	actionTable[88][RIGHT_SQUARE] = -52;
	actionTable[88][SEMI_COLON] = -52;
	actionTable[88][RIGHT_PARENTHESIS] = -52;
	actionTable[88][COMMA] = -52;
	actionTable[88][AND] = -52;
	actionTable[88][OR] = -52;
	actionTable[88][LESS_THAN] = -52;
	actionTable[88][GREATER_THAN] = -52;
	actionTable[88][LESS_OR_EQUAL] = -52;
	actionTable[88][GREATER_OR_EQUAL] = -52;
	actionTable[88][EQUAL_EQUAL] = -52;
	actionTable[88][NOT_EQUAL] = -52;
	actionTable[88][PLUS] = -52;
	actionTable[88][MINUS] = -52;
	actionTable[88][TIMES] = -52;
	actionTable[88][DIVIDE] = -52;

	//State: 89
	actionTable[89][LEFT_SQUARE] = 81;
	actionTable[89][RIGHT_SQUARE] = -53;
	actionTable[89][SEMI_COLON] = -53;
	actionTable[89][RIGHT_PARENTHESIS] = -53;
	actionTable[89][COMMA] = -53;
	actionTable[89][AND] = -53;
	actionTable[89][OR] = -53;
	actionTable[89][LESS_THAN] = -53;
	actionTable[89][GREATER_THAN] = -53;
	actionTable[89][LESS_OR_EQUAL] = -53;
	actionTable[89][GREATER_OR_EQUAL] = -53;
	actionTable[89][EQUAL_EQUAL] = -53;
	actionTable[89][NOT_EQUAL] = -53;
	actionTable[89][PLUS] = -53;
	actionTable[89][MINUS] = -53;
	actionTable[89][TIMES] = -53;
	actionTable[89][DIVIDE] = -53;
	actionTable[89][PLUS_PLUS] = 126;
	actionTable[89][MINUS_MINUS] = 127;
	actionTable[89][DOT] = 80;

	//State: 90
	actionTable[90][ID] = 22;
	actionTable[90][LV] = 128;
	actionTable[90][IDU] = 71;

	//State: 91
	actionTable[91][ID] = 22;
	actionTable[91][LV] = 129;
	actionTable[91][IDU] = 71;

	//State: 92
	actionTable[92][LEFT_PARENTHESIS] = 92;
	actionTable[92][MINUS] = 94;
	actionTable[92][PLUS_PLUS] = 90;
	actionTable[92][MINUS_MINUS] = 91;
	actionTable[92][NOT] = 95;
	actionTable[92][TRUE] = 101;
	actionTable[92][FALSE] = 102;
	actionTable[92][CHARACTER] = 103;
	actionTable[92][STRINGVAL] = 104;
	actionTable[92][NUMERAL] = 31;
	actionTable[92][ID] = 22;
	actionTable[92][E] = 130;
	actionTable[92][L] = 85;
	actionTable[92][R] = 86;
	actionTable[92][Y] = 87;
	actionTable[92][F] = 88;
	actionTable[92][LV] = 89;
	actionTable[92][TRU] = 96;
	actionTable[92][FALS] = 97;
	actionTable[92][CH] = 98;
	actionTable[92][ST] = 99;
	actionTable[92][NU] = 100;
	actionTable[92][IDU] = 93;

	//State: 93
	actionTable[93][LEFT_SQUARE] = -72;
	actionTable[93][RIGHT_SQUARE] = -72;
	actionTable[93][SEMI_COLON] = -72;
	actionTable[93][LEFT_PARENTHESIS] = -85;
	actionTable[93][RIGHT_PARENTHESIS] = -72;
	actionTable[93][COMMA] = -72;
	actionTable[93][AND] = -72;
	actionTable[93][OR] = -72;
	actionTable[93][LESS_THAN] = -72;
	actionTable[93][GREATER_THAN] = -72;
	actionTable[93][LESS_OR_EQUAL] = -72;
	actionTable[93][GREATER_OR_EQUAL] = -72;
	actionTable[93][EQUAL_EQUAL] = -72;
	actionTable[93][NOT_EQUAL] = -72;
	actionTable[93][PLUS] = -72;
	actionTable[93][MINUS] = -72;
	actionTable[93][TIMES] = -72;
	actionTable[93][DIVIDE] = -72;
	actionTable[93][PLUS_PLUS] = -72;
	actionTable[93][MINUS_MINUS] = -72;
	actionTable[93][DOT] = -72;
	actionTable[93][MC] = 131;

	//State: 94
	actionTable[94][LEFT_PARENTHESIS] = 92;
	actionTable[94][MINUS] = 94;
	actionTable[94][PLUS_PLUS] = 90;
	actionTable[94][MINUS_MINUS] = 91;
	actionTable[94][NOT] = 95;
	actionTable[94][TRUE] = 101;
	actionTable[94][FALSE] = 102;
	actionTable[94][CHARACTER] = 103;
	actionTable[94][STRINGVAL] = 104;
	actionTable[94][NUMERAL] = 31;
	actionTable[94][ID] = 22;
	actionTable[94][F] = 132;
	actionTable[94][LV] = 89;
	actionTable[94][TRU] = 96;
	actionTable[94][FALS] = 97;
	actionTable[94][CH] = 98;
	actionTable[94][ST] = 99;
	actionTable[94][NU] = 100;
	actionTable[94][IDU] = 93;

	//State: 95
	actionTable[95][LEFT_PARENTHESIS] = 92;
	actionTable[95][MINUS] = 94;
	actionTable[95][PLUS_PLUS] = 90;
	actionTable[95][MINUS_MINUS] = 91;
	actionTable[95][NOT] = 95;
	actionTable[95][TRUE] = 101;
	actionTable[95][FALSE] = 102;
	actionTable[95][CHARACTER] = 103;
	actionTable[95][STRINGVAL] = 104;
	actionTable[95][NUMERAL] = 31;
	actionTable[95][ID] = 22;
	actionTable[95][F] = 133;
	actionTable[95][LV] = 89;
	actionTable[95][TRU] = 96;
	actionTable[95][FALS] = 97;
	actionTable[95][CH] = 98;
	actionTable[95][ST] = 99;
	actionTable[95][NU] = 100;
	actionTable[95][IDU] = 93;

	//State: 96
	actionTable[96][RIGHT_SQUARE] = -62;
	actionTable[96][SEMI_COLON] = -62;
	actionTable[96][RIGHT_PARENTHESIS] = -62;
	actionTable[96][COMMA] = -62;
	actionTable[96][AND] = -62;
	actionTable[96][OR] = -62;
	actionTable[96][LESS_THAN] = -62;
	actionTable[96][GREATER_THAN] = -62;
	actionTable[96][LESS_OR_EQUAL] = -62;
	actionTable[96][GREATER_OR_EQUAL] = -62;
	actionTable[96][EQUAL_EQUAL] = -62;
	actionTable[96][NOT_EQUAL] = -62;
	actionTable[96][PLUS] = -62;
	actionTable[96][MINUS] = -62;
	actionTable[96][TIMES] = -62;
	actionTable[96][DIVIDE] = -62;

	//State: 97
	actionTable[97][RIGHT_SQUARE] = -63;
	actionTable[97][SEMI_COLON] = -63;
	actionTable[97][RIGHT_PARENTHESIS] = -63;
	actionTable[97][COMMA] = -63;
	actionTable[97][AND] = -63;
	actionTable[97][OR] = -63;
	actionTable[97][LESS_THAN] = -63;
	actionTable[97][GREATER_THAN] = -63;
	actionTable[97][LESS_OR_EQUAL] = -63;
	actionTable[97][GREATER_OR_EQUAL] = -63;
	actionTable[97][EQUAL_EQUAL] = -63;
	actionTable[97][NOT_EQUAL] = -63;
	actionTable[97][PLUS] = -63;
	actionTable[97][MINUS] = -63;
	actionTable[97][TIMES] = -63;
	actionTable[97][DIVIDE] = -63;

	//State: 98
	actionTable[98][RIGHT_SQUARE] = -64;
	actionTable[98][SEMI_COLON] = -64;
	actionTable[98][RIGHT_PARENTHESIS] = -64;
	actionTable[98][COMMA] = -64;
	actionTable[98][AND] = -64;
	actionTable[98][OR] = -64;
	actionTable[98][LESS_THAN] = -64;
	actionTable[98][GREATER_THAN] = -64;
	actionTable[98][LESS_OR_EQUAL] = -64;
	actionTable[98][GREATER_OR_EQUAL] = -64;
	actionTable[98][EQUAL_EQUAL] = -64;
	actionTable[98][NOT_EQUAL] = -64;
	actionTable[98][PLUS] = -64;
	actionTable[98][MINUS] = -64;
	actionTable[98][TIMES] = -64;
	actionTable[98][DIVIDE] = -64;

	//State: 99
	actionTable[99][RIGHT_SQUARE] = -65;
	actionTable[99][SEMI_COLON] = -65;
	actionTable[99][RIGHT_PARENTHESIS] = -65;
	actionTable[99][COMMA] = -65;
	actionTable[99][AND] = -65;
	actionTable[99][OR] = -65;
	actionTable[99][LESS_THAN] = -65;
	actionTable[99][GREATER_THAN] = -65;
	actionTable[99][LESS_OR_EQUAL] = -65;
	actionTable[99][GREATER_OR_EQUAL] = -65;
	actionTable[99][EQUAL_EQUAL] = -65;
	actionTable[99][NOT_EQUAL] = -65;
	actionTable[99][PLUS] = -65;
	actionTable[99][MINUS] = -65;
	actionTable[99][TIMES] = -65;
	actionTable[99][DIVIDE] = -65;

	//State: 100
	actionTable[100][RIGHT_SQUARE] = -66;
	actionTable[100][SEMI_COLON] = -66;
	actionTable[100][RIGHT_PARENTHESIS] = -66;
	actionTable[100][COMMA] = -66;
	actionTable[100][AND] = -66;
	actionTable[100][OR] = -66;
	actionTable[100][LESS_THAN] = -66;
	actionTable[100][GREATER_THAN] = -66;
	actionTable[100][LESS_OR_EQUAL] = -66;
	actionTable[100][GREATER_OR_EQUAL] = -66;
	actionTable[100][EQUAL_EQUAL] = -66;
	actionTable[100][NOT_EQUAL] = -66;
	actionTable[100][PLUS] = -66;
	actionTable[100][MINUS] = -66;
	actionTable[100][TIMES] = -66;
	actionTable[100][DIVIDE] = -66;

	//State: 101
	actionTable[101][RIGHT_SQUARE] = -73;
	actionTable[101][SEMI_COLON] = -73;
	actionTable[101][RIGHT_PARENTHESIS] = -73;
	actionTable[101][COMMA] = -73;
	actionTable[101][AND] = -73;
	actionTable[101][OR] = -73;
	actionTable[101][LESS_THAN] = -73;
	actionTable[101][GREATER_THAN] = -73;
	actionTable[101][LESS_OR_EQUAL] = -73;
	actionTable[101][GREATER_OR_EQUAL] = -73;
	actionTable[101][EQUAL_EQUAL] = -73;
	actionTable[101][NOT_EQUAL] = -73;
	actionTable[101][PLUS] = -73;
	actionTable[101][MINUS] = -73;
	actionTable[101][TIMES] = -73;
	actionTable[101][DIVIDE] = -73;

	//State: 102
	actionTable[102][RIGHT_SQUARE] = -74;
	actionTable[102][SEMI_COLON] = -74;
	actionTable[102][RIGHT_PARENTHESIS] = -74;
	actionTable[102][COMMA] = -74;
	actionTable[102][AND] = -74;
	actionTable[102][OR] = -74;
	actionTable[102][LESS_THAN] = -74;
	actionTable[102][GREATER_THAN] = -74;
	actionTable[102][LESS_OR_EQUAL] = -74;
	actionTable[102][GREATER_OR_EQUAL] = -74;
	actionTable[102][EQUAL_EQUAL] = -74;
	actionTable[102][NOT_EQUAL] = -74;
	actionTable[102][PLUS] = -74;
	actionTable[102][MINUS] = -74;
	actionTable[102][TIMES] = -74;
	actionTable[102][DIVIDE] = -74;

	//State: 103
	actionTable[103][RIGHT_SQUARE] = -75;
	actionTable[103][SEMI_COLON] = -75;
	actionTable[103][RIGHT_PARENTHESIS] = -75;
	actionTable[103][COMMA] = -75;
	actionTable[103][AND] = -75;
	actionTable[103][OR] = -75;
	actionTable[103][LESS_THAN] = -75;
	actionTable[103][GREATER_THAN] = -75;
	actionTable[103][LESS_OR_EQUAL] = -75;
	actionTable[103][GREATER_OR_EQUAL] = -75;
	actionTable[103][EQUAL_EQUAL] = -75;
	actionTable[103][NOT_EQUAL] = -75;
	actionTable[103][PLUS] = -75;
	actionTable[103][MINUS] = -75;
	actionTable[103][TIMES] = -75;
	actionTable[103][DIVIDE] = -75;

	//State: 104
	actionTable[104][RIGHT_SQUARE] = -76;
	actionTable[104][SEMI_COLON] = -76;
	actionTable[104][RIGHT_PARENTHESIS] = -76;
	actionTable[104][COMMA] = -76;
	actionTable[104][AND] = -76;
	actionTable[104][OR] = -76;
	actionTable[104][LESS_THAN] = -76;
	actionTable[104][GREATER_THAN] = -76;
	actionTable[104][LESS_OR_EQUAL] = -76;
	actionTable[104][GREATER_OR_EQUAL] = -76;
	actionTable[104][EQUAL_EQUAL] = -76;
	actionTable[104][NOT_EQUAL] = -76;
	actionTable[104][PLUS] = -76;
	actionTable[104][MINUS] = -76;
	actionTable[104][TIMES] = -76;
	actionTable[104][DIVIDE] = -76;

	//State: 105
	actionTable[105][INTEGER] = 17;
	actionTable[105][CHAR] = 18;
	actionTable[105][BOOLEAN] = 19;
	actionTable[105][STRING] = 20;
	actionTable[105][ID] = 22;
	actionTable[105][T] = 134;
	actionTable[105][IDU] = 21;

	//State: 106
	actionTable[106][RIGHT_PARENTHESIS] = 135;
	actionTable[106][AND] = 114;
	actionTable[106][OR] = 115;

	//State: 107
	actionTable[107][LEFT_PARENTHESIS] = 92;
	actionTable[107][MINUS] = 94;
	actionTable[107][PLUS_PLUS] = 90;
	actionTable[107][MINUS_MINUS] = 91;
	actionTable[107][NOT] = 95;
	actionTable[107][TRUE] = 101;
	actionTable[107][FALSE] = 102;
	actionTable[107][CHARACTER] = 103;
	actionTable[107][STRINGVAL] = 104;
	actionTable[107][NUMERAL] = 31;
	actionTable[107][ID] = 22;
	actionTable[107][E] = 136;
	actionTable[107][L] = 85;
	actionTable[107][R] = 86;
	actionTable[107][Y] = 87;
	actionTable[107][F] = 88;
	actionTable[107][LV] = 89;
	actionTable[107][TRU] = 96;
	actionTable[107][FALS] = 97;
	actionTable[107][CH] = 98;
	actionTable[107][ST] = 99;
	actionTable[107][NU] = 100;
	actionTable[107][IDU] = 93;

	//State: 108
	actionTable[108][WHILE] = 137;

	//State: 109
	actionTable[109][LEFT_PARENTHESIS] = 92;
	actionTable[109][MINUS] = 94;
	actionTable[109][PLUS_PLUS] = 90;
	actionTable[109][MINUS_MINUS] = 91;
	actionTable[109][NOT] = 95;
	actionTable[109][TRUE] = 101;
	actionTable[109][FALSE] = 102;
	actionTable[109][CHARACTER] = 103;
	actionTable[109][STRINGVAL] = 104;
	actionTable[109][NUMERAL] = 31;
	actionTable[109][ID] = 22;
	actionTable[109][E] = 138;
	actionTable[109][L] = 85;
	actionTable[109][R] = 86;
	actionTable[109][Y] = 87;
	actionTable[109][F] = 88;
	actionTable[109][LV] = 89;
	actionTable[109][TRU] = 96;
	actionTable[109][FALS] = 97;
	actionTable[109][CH] = 98;
	actionTable[109][ST] = 99;
	actionTable[109][NU] = 100;
	actionTable[109][IDU] = 93;

	//State: 110
	actionTable[110][EQUALS] = -70;
	actionTable[110][LEFT_SQUARE] = -70;
	actionTable[110][RIGHT_SQUARE] = -70;
	actionTable[110][LEFT_BRACES] = -70;
	actionTable[110][RIGHT_BRACES] = -70;
	actionTable[110][SEMI_COLON] = -70;
	actionTable[110][RIGHT_PARENTHESIS] = -70;
	actionTable[110][COMMA] = -70;
	actionTable[110][IF] = -70;
	actionTable[110][ELSE] = -70;
	actionTable[110][WHILE] = -70;
	actionTable[110][DO] = -70;
	actionTable[110][BREAK] = -70;
	actionTable[110][CONTINUE] = -70;
	actionTable[110][RETURN] = -70;
	actionTable[110][AND] = -70;
	actionTable[110][OR] = -70;
	actionTable[110][LESS_THAN] = -70;
	actionTable[110][GREATER_THAN] = -70;
	actionTable[110][LESS_OR_EQUAL] = -70;
	actionTable[110][GREATER_OR_EQUAL] = -70;
	actionTable[110][EQUAL_EQUAL] = -70;
	actionTable[110][NOT_EQUAL] = -70;
	actionTable[110][PLUS] = -70;
	actionTable[110][MINUS] = -70;
	actionTable[110][TIMES] = -70;
	actionTable[110][DIVIDE] = -70;
	actionTable[110][PLUS_PLUS] = -70;
	actionTable[110][MINUS_MINUS] = -70;
	actionTable[110][DOT] = -70;
	actionTable[110][ID] = -70;

	//State: 111
	actionTable[111][EQUALS] = -78;
	actionTable[111][LEFT_SQUARE] = -78;
	actionTable[111][RIGHT_SQUARE] = -78;
	actionTable[111][LEFT_BRACES] = -78;
	actionTable[111][RIGHT_BRACES] = -78;
	actionTable[111][SEMI_COLON] = -78;
	actionTable[111][RIGHT_PARENTHESIS] = -78;
	actionTable[111][COMMA] = -78;
	actionTable[111][IF] = -78;
	actionTable[111][ELSE] = -78;
	actionTable[111][WHILE] = -78;
	actionTable[111][DO] = -78;
	actionTable[111][BREAK] = -78;
	actionTable[111][CONTINUE] = -78;
	actionTable[111][RETURN] = -78;
	actionTable[111][AND] = -78;
	actionTable[111][OR] = -78;
	actionTable[111][LESS_THAN] = -78;
	actionTable[111][GREATER_THAN] = -78;
	actionTable[111][LESS_OR_EQUAL] = -78;
	actionTable[111][GREATER_OR_EQUAL] = -78;
	actionTable[111][EQUAL_EQUAL] = -78;
	actionTable[111][NOT_EQUAL] = -78;
	actionTable[111][PLUS] = -78;
	actionTable[111][MINUS] = -78;
	actionTable[111][TIMES] = -78;
	actionTable[111][DIVIDE] = -78;
	actionTable[111][PLUS_PLUS] = -78;
	actionTable[111][MINUS_MINUS] = -78;
	actionTable[111][DOT] = -78;
	actionTable[111][ID] = -78;

	//State: 112
	actionTable[112][RIGHT_SQUARE] = 139;
	actionTable[112][AND] = 114;
	actionTable[112][OR] = 115;

	//State: 113
	actionTable[113][LEFT_BRACES] = -36;
	actionTable[113][RIGHT_BRACES] = -36;
	actionTable[113][IF] = -36;
	actionTable[113][ELSE] = -36;
	actionTable[113][WHILE] = -36;
	actionTable[113][DO] = -36;
	actionTable[113][BREAK] = -36;
	actionTable[113][CONTINUE] = -36;
	actionTable[113][RETURN] = -36;
	actionTable[113][ID] = -36;

	//State: 114
	actionTable[114][LEFT_PARENTHESIS] = 92;
	actionTable[114][MINUS] = 94;
	actionTable[114][PLUS_PLUS] = 90;
	actionTable[114][MINUS_MINUS] = 91;
	actionTable[114][NOT] = 95;
	actionTable[114][TRUE] = 101;
	actionTable[114][FALSE] = 102;
	actionTable[114][CHARACTER] = 103;
	actionTable[114][STRINGVAL] = 104;
	actionTable[114][NUMERAL] = 31;
	actionTable[114][ID] = 22;
	actionTable[114][L] = 140;
	actionTable[114][R] = 86;
	actionTable[114][Y] = 87;
	actionTable[114][F] = 88;
	actionTable[114][LV] = 89;
	actionTable[114][TRU] = 96;
	actionTable[114][FALS] = 97;
	actionTable[114][CH] = 98;
	actionTable[114][ST] = 99;
	actionTable[114][NU] = 100;
	actionTable[114][IDU] = 93;

	//State: 115
	actionTable[115][LEFT_PARENTHESIS] = 92;
	actionTable[115][MINUS] = 94;
	actionTable[115][PLUS_PLUS] = 90;
	actionTable[115][MINUS_MINUS] = 91;
	actionTable[115][NOT] = 95;
	actionTable[115][TRUE] = 101;
	actionTable[115][FALSE] = 102;
	actionTable[115][CHARACTER] = 103;
	actionTable[115][STRINGVAL] = 104;
	actionTable[115][NUMERAL] = 31;
	actionTable[115][ID] = 22;
	actionTable[115][L] = 141;
	actionTable[115][R] = 86;
	actionTable[115][Y] = 87;
	actionTable[115][F] = 88;
	actionTable[115][LV] = 89;
	actionTable[115][TRU] = 96;
	actionTable[115][FALS] = 97;
	actionTable[115][CH] = 98;
	actionTable[115][ST] = 99;
	actionTable[115][NU] = 100;
	actionTable[115][IDU] = 93;

	//State: 116
	actionTable[116][LEFT_PARENTHESIS] = 92;
	actionTable[116][MINUS] = 94;
	actionTable[116][PLUS_PLUS] = 90;
	actionTable[116][MINUS_MINUS] = 91;
	actionTable[116][NOT] = 95;
	actionTable[116][TRUE] = 101;
	actionTable[116][FALSE] = 102;
	actionTable[116][CHARACTER] = 103;
	actionTable[116][STRINGVAL] = 104;
	actionTable[116][NUMERAL] = 31;
	actionTable[116][ID] = 22;
	actionTable[116][R] = 142;
	actionTable[116][Y] = 87;
	actionTable[116][F] = 88;
	actionTable[116][LV] = 89;
	actionTable[116][TRU] = 96;
	actionTable[116][FALS] = 97;
	actionTable[116][CH] = 98;
	actionTable[116][ST] = 99;
	actionTable[116][NU] = 100;
	actionTable[116][IDU] = 93;

	//State: 117
	actionTable[117][LEFT_PARENTHESIS] = 92;
	actionTable[117][MINUS] = 94;
	actionTable[117][PLUS_PLUS] = 90;
	actionTable[117][MINUS_MINUS] = 91;
	actionTable[117][NOT] = 95;
	actionTable[117][TRUE] = 101;
	actionTable[117][FALSE] = 102;
	actionTable[117][CHARACTER] = 103;
	actionTable[117][STRINGVAL] = 104;
	actionTable[117][NUMERAL] = 31;
	actionTable[117][ID] = 22;
	actionTable[117][R] = 143;
	actionTable[117][Y] = 87;
	actionTable[117][F] = 88;
	actionTable[117][LV] = 89;
	actionTable[117][TRU] = 96;
	actionTable[117][FALS] = 97;
	actionTable[117][CH] = 98;
	actionTable[117][ST] = 99;
	actionTable[117][NU] = 100;
	actionTable[117][IDU] = 93;

	//State: 118
	actionTable[118][LEFT_PARENTHESIS] = 92;
	actionTable[118][MINUS] = 94;
	actionTable[118][PLUS_PLUS] = 90;
	actionTable[118][MINUS_MINUS] = 91;
	actionTable[118][NOT] = 95;
	actionTable[118][TRUE] = 101;
	actionTable[118][FALSE] = 102;
	actionTable[118][CHARACTER] = 103;
	actionTable[118][STRINGVAL] = 104;
	actionTable[118][NUMERAL] = 31;
	actionTable[118][ID] = 22;
	actionTable[118][R] = 144;
	actionTable[118][Y] = 87;
	actionTable[118][F] = 88;
	actionTable[118][LV] = 89;
	actionTable[118][TRU] = 96;
	actionTable[118][FALS] = 97;
	actionTable[118][CH] = 98;
	actionTable[118][ST] = 99;
	actionTable[118][NU] = 100;
	actionTable[118][IDU] = 93;

	//State: 119
	actionTable[119][LEFT_PARENTHESIS] = 92;
	actionTable[119][MINUS] = 94;
	actionTable[119][PLUS_PLUS] = 90;
	actionTable[119][MINUS_MINUS] = 91;
	actionTable[119][NOT] = 95;
	actionTable[119][TRUE] = 101;
	actionTable[119][FALSE] = 102;
	actionTable[119][CHARACTER] = 103;
	actionTable[119][STRINGVAL] = 104;
	actionTable[119][NUMERAL] = 31;
	actionTable[119][ID] = 22;
	actionTable[119][R] = 145;
	actionTable[119][Y] = 87;
	actionTable[119][F] = 88;
	actionTable[119][LV] = 89;
	actionTable[119][TRU] = 96;
	actionTable[119][FALS] = 97;
	actionTable[119][CH] = 98;
	actionTable[119][ST] = 99;
	actionTable[119][NU] = 100;
	actionTable[119][IDU] = 93;

	//State: 120
	actionTable[120][LEFT_PARENTHESIS] = 92;
	actionTable[120][MINUS] = 94;
	actionTable[120][PLUS_PLUS] = 90;
	actionTable[120][MINUS_MINUS] = 91;
	actionTable[120][NOT] = 95;
	actionTable[120][TRUE] = 101;
	actionTable[120][FALSE] = 102;
	actionTable[120][CHARACTER] = 103;
	actionTable[120][STRINGVAL] = 104;
	actionTable[120][NUMERAL] = 31;
	actionTable[120][ID] = 22;
	actionTable[120][R] = 146;
	actionTable[120][Y] = 87;
	actionTable[120][F] = 88;
	actionTable[120][LV] = 89;
	actionTable[120][TRU] = 96;
	actionTable[120][FALS] = 97;
	actionTable[120][CH] = 98;
	actionTable[120][ST] = 99;
	actionTable[120][NU] = 100;
	actionTable[120][IDU] = 93;

	//State: 121
	actionTable[121][LEFT_PARENTHESIS] = 92;
	actionTable[121][MINUS] = 94;
	actionTable[121][PLUS_PLUS] = 90;
	actionTable[121][MINUS_MINUS] = 91;
	actionTable[121][NOT] = 95;
	actionTable[121][TRUE] = 101;
	actionTable[121][FALSE] = 102;
	actionTable[121][CHARACTER] = 103;
	actionTable[121][STRINGVAL] = 104;
	actionTable[121][NUMERAL] = 31;
	actionTable[121][ID] = 22;
	actionTable[121][R] = 147;
	actionTable[121][Y] = 87;
	actionTable[121][F] = 88;
	actionTable[121][LV] = 89;
	actionTable[121][TRU] = 96;
	actionTable[121][FALS] = 97;
	actionTable[121][CH] = 98;
	actionTable[121][ST] = 99;
	actionTable[121][NU] = 100;
	actionTable[121][IDU] = 93;

	//State: 122
	actionTable[122][LEFT_PARENTHESIS] = 92;
	actionTable[122][MINUS] = 94;
	actionTable[122][PLUS_PLUS] = 90;
	actionTable[122][MINUS_MINUS] = 91;
	actionTable[122][NOT] = 95;
	actionTable[122][TRUE] = 101;
	actionTable[122][FALSE] = 102;
	actionTable[122][CHARACTER] = 103;
	actionTable[122][STRINGVAL] = 104;
	actionTable[122][NUMERAL] = 31;
	actionTable[122][ID] = 22;
	actionTable[122][Y] = 148;
	actionTable[122][F] = 88;
	actionTable[122][LV] = 89;
	actionTable[122][TRU] = 96;
	actionTable[122][FALS] = 97;
	actionTable[122][CH] = 98;
	actionTable[122][ST] = 99;
	actionTable[122][NU] = 100;
	actionTable[122][IDU] = 93;

	//State: 123
	actionTable[123][LEFT_PARENTHESIS] = 92;
	actionTable[123][MINUS] = 94;
	actionTable[123][PLUS_PLUS] = 90;
	actionTable[123][MINUS_MINUS] = 91;
	actionTable[123][NOT] = 95;
	actionTable[123][TRUE] = 101;
	actionTable[123][FALSE] = 102;
	actionTable[123][CHARACTER] = 103;
	actionTable[123][STRINGVAL] = 104;
	actionTable[123][NUMERAL] = 31;
	actionTable[123][ID] = 22;
	actionTable[123][Y] = 149;
	actionTable[123][F] = 88;
	actionTable[123][LV] = 89;
	actionTable[123][TRU] = 96;
	actionTable[123][FALS] = 97;
	actionTable[123][CH] = 98;
	actionTable[123][ST] = 99;
	actionTable[123][NU] = 100;
	actionTable[123][IDU] = 93;

	//State: 124
	actionTable[124][LEFT_PARENTHESIS] = 92;
	actionTable[124][MINUS] = 94;
	actionTable[124][PLUS_PLUS] = 90;
	actionTable[124][MINUS_MINUS] = 91;
	actionTable[124][NOT] = 95;
	actionTable[124][TRUE] = 101;
	actionTable[124][FALSE] = 102;
	actionTable[124][CHARACTER] = 103;
	actionTable[124][STRINGVAL] = 104;
	actionTable[124][NUMERAL] = 31;
	actionTable[124][ID] = 22;
	actionTable[124][F] = 150;
	actionTable[124][LV] = 89;
	actionTable[124][TRU] = 96;
	actionTable[124][FALS] = 97;
	actionTable[124][CH] = 98;
	actionTable[124][ST] = 99;
	actionTable[124][NU] = 100;
	actionTable[124][IDU] = 93;

	//State: 125
	actionTable[125][LEFT_PARENTHESIS] = 92;
	actionTable[125][MINUS] = 94;
	actionTable[125][PLUS_PLUS] = 90;
	actionTable[125][MINUS_MINUS] = 91;
	actionTable[125][NOT] = 95;
	actionTable[125][TRUE] = 101;
	actionTable[125][FALSE] = 102;
	actionTable[125][CHARACTER] = 103;
	actionTable[125][STRINGVAL] = 104;
	actionTable[125][NUMERAL] = 31;
	actionTable[125][ID] = 22;
	actionTable[125][F] = 151;
	actionTable[125][LV] = 89;
	actionTable[125][TRU] = 96;
	actionTable[125][FALS] = 97;
	actionTable[125][CH] = 98;
	actionTable[125][ST] = 99;
	actionTable[125][NU] = 100;
	actionTable[125][IDU] = 93;

	//State: 126
	actionTable[126][RIGHT_SQUARE] = -56;
	actionTable[126][SEMI_COLON] = -56;
	actionTable[126][RIGHT_PARENTHESIS] = -56;
	actionTable[126][COMMA] = -56;
	actionTable[126][AND] = -56;
	actionTable[126][OR] = -56;
	actionTable[126][LESS_THAN] = -56;
	actionTable[126][GREATER_THAN] = -56;
	actionTable[126][LESS_OR_EQUAL] = -56;
	actionTable[126][GREATER_OR_EQUAL] = -56;
	actionTable[126][EQUAL_EQUAL] = -56;
	actionTable[126][NOT_EQUAL] = -56;
	actionTable[126][PLUS] = -56;
	actionTable[126][MINUS] = -56;
	actionTable[126][TIMES] = -56;
	actionTable[126][DIVIDE] = -56;

	//State: 127
	actionTable[127][RIGHT_SQUARE] = -57;
	actionTable[127][SEMI_COLON] = -57;
	actionTable[127][RIGHT_PARENTHESIS] = -57;
	actionTable[127][COMMA] = -57;
	actionTable[127][AND] = -57;
	actionTable[127][OR] = -57;
	actionTable[127][LESS_THAN] = -57;
	actionTable[127][GREATER_THAN] = -57;
	actionTable[127][LESS_OR_EQUAL] = -57;
	actionTable[127][GREATER_OR_EQUAL] = -57;
	actionTable[127][EQUAL_EQUAL] = -57;
	actionTable[127][NOT_EQUAL] = -57;
	actionTable[127][PLUS] = -57;
	actionTable[127][MINUS] = -57;
	actionTable[127][TIMES] = -57;
	actionTable[127][DIVIDE] = -57;

	//State: 128
	actionTable[128][LEFT_SQUARE] = 81;
	actionTable[128][RIGHT_SQUARE] = -54;
	actionTable[128][SEMI_COLON] = -54;
	actionTable[128][RIGHT_PARENTHESIS] = -54;
	actionTable[128][COMMA] = -54;
	actionTable[128][AND] = -54;
	actionTable[128][OR] = -54;
	actionTable[128][LESS_THAN] = -54;
	actionTable[128][GREATER_THAN] = -54;
	actionTable[128][LESS_OR_EQUAL] = -54;
	actionTable[128][GREATER_OR_EQUAL] = -54;
	actionTable[128][EQUAL_EQUAL] = -54;
	actionTable[128][NOT_EQUAL] = -54;
	actionTable[128][PLUS] = -54;
	actionTable[128][MINUS] = -54;
	actionTable[128][TIMES] = -54;
	actionTable[128][DIVIDE] = -54;
	actionTable[128][DOT] = 80;

	//State: 129
	actionTable[129][LEFT_SQUARE] = 81;
	actionTable[129][RIGHT_SQUARE] = -55;
	actionTable[129][SEMI_COLON] = -55;
	actionTable[129][RIGHT_PARENTHESIS] = -55;
	actionTable[129][COMMA] = -55;
	actionTable[129][AND] = -55;
	actionTable[129][OR] = -55;
	actionTable[129][LESS_THAN] = -55;
	actionTable[129][GREATER_THAN] = -55;
	actionTable[129][LESS_OR_EQUAL] = -55;
	actionTable[129][GREATER_OR_EQUAL] = -55;
	actionTable[129][EQUAL_EQUAL] = -55;
	actionTable[129][NOT_EQUAL] = -55;
	actionTable[129][PLUS] = -55;
	actionTable[129][MINUS] = -55;
	actionTable[129][TIMES] = -55;
	actionTable[129][DIVIDE] = -55;
	actionTable[129][DOT] = 80;

	//State: 130
	actionTable[130][RIGHT_PARENTHESIS] = 152;
	actionTable[130][AND] = 114;
	actionTable[130][OR] = 115;

	//State: 131
	actionTable[131][LEFT_PARENTHESIS] = 153;

	//State: 132
	actionTable[132][RIGHT_SQUARE] = -60;
	actionTable[132][SEMI_COLON] = -60;
	actionTable[132][RIGHT_PARENTHESIS] = -60;
	actionTable[132][COMMA] = -60;
	actionTable[132][AND] = -60;
	actionTable[132][OR] = -60;
	actionTable[132][LESS_THAN] = -60;
	actionTable[132][GREATER_THAN] = -60;
	actionTable[132][LESS_OR_EQUAL] = -60;
	actionTable[132][GREATER_OR_EQUAL] = -60;
	actionTable[132][EQUAL_EQUAL] = -60;
	actionTable[132][NOT_EQUAL] = -60;
	actionTable[132][PLUS] = -60;
	actionTable[132][MINUS] = -60;
	actionTable[132][TIMES] = -60;
	actionTable[132][DIVIDE] = -60;

	//State: 133
	actionTable[133][RIGHT_SQUARE] = -61;
	actionTable[133][SEMI_COLON] = -61;
	actionTable[133][RIGHT_PARENTHESIS] = -61;
	actionTable[133][COMMA] = -61;
	actionTable[133][AND] = -61;
	actionTable[133][OR] = -61;
	actionTable[133][LESS_THAN] = -61;
	actionTable[133][GREATER_THAN] = -61;
	actionTable[133][LESS_OR_EQUAL] = -61;
	actionTable[133][GREATER_OR_EQUAL] = -61;
	actionTable[133][EQUAL_EQUAL] = -61;
	actionTable[133][NOT_EQUAL] = -61;
	actionTable[133][PLUS] = -61;
	actionTable[133][MINUS] = -61;
	actionTable[133][TIMES] = -61;
	actionTable[133][DIVIDE] = -61;

	//State: 134
	actionTable[134][SEMI_COLON] = 154;

	//State: 135
	actionTable[135][LEFT_BRACES] = -87;
	actionTable[135][RIGHT_BRACES] = -87;
	actionTable[135][IF] = -87;
	actionTable[135][ELSE] = -87;
	actionTable[135][WHILE] = -87;
	actionTable[135][DO] = -87;
	actionTable[135][BREAK] = -87;
	actionTable[135][CONTINUE] = -87;
	actionTable[135][RETURN] = -87;
	actionTable[135][ID] = -87;
	actionTable[135][MT] = 155;

	//State: 136
	actionTable[136][RIGHT_PARENTHESIS] = 156;
	actionTable[136][AND] = 114;
	actionTable[136][OR] = 115;

	//State: 137
	actionTable[137][LEFT_PARENTHESIS] = 157;

	//State: 138
	actionTable[138][SEMI_COLON] = 158;
	actionTable[138][AND] = 114;
	actionTable[138][OR] = 115;

	//State: 139
	actionTable[139][EQUALS] = -71;
	actionTable[139][LEFT_SQUARE] = -71;
	actionTable[139][RIGHT_SQUARE] = -71;
	actionTable[139][LEFT_BRACES] = -71;
	actionTable[139][RIGHT_BRACES] = -71;
	actionTable[139][SEMI_COLON] = -71;
	actionTable[139][RIGHT_PARENTHESIS] = -71;
	actionTable[139][COMMA] = -71;
	actionTable[139][IF] = -71;
	actionTable[139][ELSE] = -71;
	actionTable[139][WHILE] = -71;
	actionTable[139][DO] = -71;
	actionTable[139][BREAK] = -71;
	actionTable[139][CONTINUE] = -71;
	actionTable[139][RETURN] = -71;
	actionTable[139][AND] = -71;
	actionTable[139][OR] = -71;
	actionTable[139][LESS_THAN] = -71;
	actionTable[139][GREATER_THAN] = -71;
	actionTable[139][LESS_OR_EQUAL] = -71;
	actionTable[139][GREATER_OR_EQUAL] = -71;
	actionTable[139][EQUAL_EQUAL] = -71;
	actionTable[139][NOT_EQUAL] = -71;
	actionTable[139][PLUS] = -71;
	actionTable[139][MINUS] = -71;
	actionTable[139][TIMES] = -71;
	actionTable[139][DIVIDE] = -71;
	actionTable[139][PLUS_PLUS] = -71;
	actionTable[139][MINUS_MINUS] = -71;
	actionTable[139][DOT] = -71;
	actionTable[139][ID] = -71;

	//State: 140
	actionTable[140][RIGHT_SQUARE] = -37;
	actionTable[140][SEMI_COLON] = -37;
	actionTable[140][RIGHT_PARENTHESIS] = -37;
	actionTable[140][COMMA] = -37;
	actionTable[140][AND] = -37;
	actionTable[140][OR] = -37;
	actionTable[140][LESS_THAN] = 116;
	actionTable[140][GREATER_THAN] = 117;
	actionTable[140][LESS_OR_EQUAL] = 118;
	actionTable[140][GREATER_OR_EQUAL] = 119;
	actionTable[140][EQUAL_EQUAL] = 120;
	actionTable[140][NOT_EQUAL] = 121;

	//State: 141
	actionTable[141][RIGHT_SQUARE] = -38;
	actionTable[141][SEMI_COLON] = -38;
	actionTable[141][RIGHT_PARENTHESIS] = -38;
	actionTable[141][COMMA] = -38;
	actionTable[141][AND] = -38;
	actionTable[141][OR] = -38;
	actionTable[141][LESS_THAN] = 116;
	actionTable[141][GREATER_THAN] = 117;
	actionTable[141][LESS_OR_EQUAL] = 118;
	actionTable[141][GREATER_OR_EQUAL] = 119;
	actionTable[141][EQUAL_EQUAL] = 120;
	actionTable[141][NOT_EQUAL] = 121;

	//State: 142
	actionTable[142][RIGHT_SQUARE] = -40;
	actionTable[142][SEMI_COLON] = -40;
	actionTable[142][RIGHT_PARENTHESIS] = -40;
	actionTable[142][COMMA] = -40;
	actionTable[142][AND] = -40;
	actionTable[142][OR] = -40;
	actionTable[142][LESS_THAN] = -40;
	actionTable[142][GREATER_THAN] = -40;
	actionTable[142][LESS_OR_EQUAL] = -40;
	actionTable[142][GREATER_OR_EQUAL] = -40;
	actionTable[142][EQUAL_EQUAL] = -40;
	actionTable[142][NOT_EQUAL] = -40;
	actionTable[142][PLUS] = 122;
	actionTable[142][MINUS] = 123;

	//State: 143
	actionTable[143][RIGHT_SQUARE] = -41;
	actionTable[143][SEMI_COLON] = -41;
	actionTable[143][RIGHT_PARENTHESIS] = -41;
	actionTable[143][COMMA] = -41;
	actionTable[143][AND] = -41;
	actionTable[143][OR] = -41;
	actionTable[143][LESS_THAN] = -41;
	actionTable[143][GREATER_THAN] = -41;
	actionTable[143][LESS_OR_EQUAL] = -41;
	actionTable[143][GREATER_OR_EQUAL] = -41;
	actionTable[143][EQUAL_EQUAL] = -41;
	actionTable[143][NOT_EQUAL] = -41;
	actionTable[143][PLUS] = 122;
	actionTable[143][MINUS] = 123;

	//State: 144
	actionTable[144][RIGHT_SQUARE] = -42;
	actionTable[144][SEMI_COLON] = -42;
	actionTable[144][RIGHT_PARENTHESIS] = -42;
	actionTable[144][COMMA] = -42;
	actionTable[144][AND] = -42;
	actionTable[144][OR] = -42;
	actionTable[144][LESS_THAN] = -42;
	actionTable[144][GREATER_THAN] = -42;
	actionTable[144][LESS_OR_EQUAL] = -42;
	actionTable[144][GREATER_OR_EQUAL] = -42;
	actionTable[144][EQUAL_EQUAL] = -42;
	actionTable[144][NOT_EQUAL] = -42;
	actionTable[144][PLUS] = 122;
	actionTable[144][MINUS] = 123;

	//State: 145
	actionTable[145][RIGHT_SQUARE] = -43;
	actionTable[145][SEMI_COLON] = -43;
	actionTable[145][RIGHT_PARENTHESIS] = -43;
	actionTable[145][COMMA] = -43;
	actionTable[145][AND] = -43;
	actionTable[145][OR] = -43;
	actionTable[145][LESS_THAN] = -43;
	actionTable[145][GREATER_THAN] = -43;
	actionTable[145][LESS_OR_EQUAL] = -43;
	actionTable[145][GREATER_OR_EQUAL] = -43;
	actionTable[145][EQUAL_EQUAL] = -43;
	actionTable[145][NOT_EQUAL] = -43;
	actionTable[145][PLUS] = 122;
	actionTable[145][MINUS] = 123;

	//State: 146
	actionTable[146][RIGHT_SQUARE] = -44;
	actionTable[146][SEMI_COLON] = -44;
	actionTable[146][RIGHT_PARENTHESIS] = -44;
	actionTable[146][COMMA] = -44;
	actionTable[146][AND] = -44;
	actionTable[146][OR] = -44;
	actionTable[146][LESS_THAN] = -44;
	actionTable[146][GREATER_THAN] = -44;
	actionTable[146][LESS_OR_EQUAL] = -44;
	actionTable[146][GREATER_OR_EQUAL] = -44;
	actionTable[146][EQUAL_EQUAL] = -44;
	actionTable[146][NOT_EQUAL] = -44;
	actionTable[146][PLUS] = 122;
	actionTable[146][MINUS] = 123;

	//State: 147
	actionTable[147][RIGHT_SQUARE] = -45;
	actionTable[147][SEMI_COLON] = -45;
	actionTable[147][RIGHT_PARENTHESIS] = -45;
	actionTable[147][COMMA] = -45;
	actionTable[147][AND] = -45;
	actionTable[147][OR] = -45;
	actionTable[147][LESS_THAN] = -45;
	actionTable[147][GREATER_THAN] = -45;
	actionTable[147][LESS_OR_EQUAL] = -45;
	actionTable[147][GREATER_OR_EQUAL] = -45;
	actionTable[147][EQUAL_EQUAL] = -45;
	actionTable[147][NOT_EQUAL] = -45;
	actionTable[147][PLUS] = 122;
	actionTable[147][MINUS] = 123;

	//State: 148
	actionTable[148][RIGHT_SQUARE] = -47;
	actionTable[148][SEMI_COLON] = -47;
	actionTable[148][RIGHT_PARENTHESIS] = -47;
	actionTable[148][COMMA] = -47;
	actionTable[148][AND] = -47;
	actionTable[148][OR] = -47;
	actionTable[148][LESS_THAN] = -47;
	actionTable[148][GREATER_THAN] = -47;
	actionTable[148][LESS_OR_EQUAL] = -47;
	actionTable[148][GREATER_OR_EQUAL] = -47;
	actionTable[148][EQUAL_EQUAL] = -47;
	actionTable[148][NOT_EQUAL] = -47;
	actionTable[148][PLUS] = -47;
	actionTable[148][MINUS] = -47;
	actionTable[148][TIMES] = 124;
	actionTable[148][DIVIDE] = 125;

	//State: 149
	actionTable[149][RIGHT_SQUARE] = -48;
	actionTable[149][SEMI_COLON] = -48;
	actionTable[149][RIGHT_PARENTHESIS] = -48;
	actionTable[149][COMMA] = -48;
	actionTable[149][AND] = -48;
	actionTable[149][OR] = -48;
	actionTable[149][LESS_THAN] = -48;
	actionTable[149][GREATER_THAN] = -48;
	actionTable[149][LESS_OR_EQUAL] = -48;
	actionTable[149][GREATER_OR_EQUAL] = -48;
	actionTable[149][EQUAL_EQUAL] = -48;
	actionTable[149][NOT_EQUAL] = -48;
	actionTable[149][PLUS] = -48;
	actionTable[149][MINUS] = -48;
	actionTable[149][TIMES] = 124;
	actionTable[149][DIVIDE] = 125;

	//State: 150
	actionTable[150][RIGHT_SQUARE] = -50;
	actionTable[150][SEMI_COLON] = -50;
	actionTable[150][RIGHT_PARENTHESIS] = -50;
	actionTable[150][COMMA] = -50;
	actionTable[150][AND] = -50;
	actionTable[150][OR] = -50;
	actionTable[150][LESS_THAN] = -50;
	actionTable[150][GREATER_THAN] = -50;
	actionTable[150][LESS_OR_EQUAL] = -50;
	actionTable[150][GREATER_OR_EQUAL] = -50;
	actionTable[150][EQUAL_EQUAL] = -50;
	actionTable[150][NOT_EQUAL] = -50;
	actionTable[150][PLUS] = -50;
	actionTable[150][MINUS] = -50;
	actionTable[150][TIMES] = -50;
	actionTable[150][DIVIDE] = -50;

	//State: 151
	actionTable[151][RIGHT_SQUARE] = -51;
	actionTable[151][SEMI_COLON] = -51;
	actionTable[151][RIGHT_PARENTHESIS] = -51;
	actionTable[151][COMMA] = -51;
	actionTable[151][AND] = -51;
	actionTable[151][OR] = -51;
	actionTable[151][LESS_THAN] = -51;
	actionTable[151][GREATER_THAN] = -51;
	actionTable[151][LESS_OR_EQUAL] = -51;
	actionTable[151][GREATER_OR_EQUAL] = -51;
	actionTable[151][EQUAL_EQUAL] = -51;
	actionTable[151][NOT_EQUAL] = -51;
	actionTable[151][PLUS] = -51;
	actionTable[151][MINUS] = -51;
	actionTable[151][TIMES] = -51;
	actionTable[151][DIVIDE] = -51;

	//State: 152
	actionTable[152][RIGHT_SQUARE] = -58;
	actionTable[152][SEMI_COLON] = -58;
	actionTable[152][RIGHT_PARENTHESIS] = -58;
	actionTable[152][COMMA] = -58;
	actionTable[152][AND] = -58;
	actionTable[152][OR] = -58;
	actionTable[152][LESS_THAN] = -58;
	actionTable[152][GREATER_THAN] = -58;
	actionTable[152][LESS_OR_EQUAL] = -58;
	actionTable[152][GREATER_OR_EQUAL] = -58;
	actionTable[152][EQUAL_EQUAL] = -58;
	actionTable[152][NOT_EQUAL] = -58;
	actionTable[152][PLUS] = -58;
	actionTable[152][MINUS] = -58;
	actionTable[152][TIMES] = -58;
	actionTable[152][DIVIDE] = -58;

	//State: 153
	actionTable[153][LEFT_PARENTHESIS] = 92;
	actionTable[153][RIGHT_PARENTHESIS] = -69;
	actionTable[153][COMMA] = -69;
	actionTable[153][MINUS] = 94;
	actionTable[153][PLUS_PLUS] = 90;
	actionTable[153][MINUS_MINUS] = 91;
	actionTable[153][NOT] = 95;
	actionTable[153][TRUE] = 101;
	actionTable[153][FALSE] = 102;
	actionTable[153][CHARACTER] = 103;
	actionTable[153][STRINGVAL] = 104;
	actionTable[153][NUMERAL] = 31;
	actionTable[153][ID] = 22;
	actionTable[153][E] = 160;
	actionTable[153][L] = 85;
	actionTable[153][R] = 86;
	actionTable[153][Y] = 87;
	actionTable[153][F] = 88;
	actionTable[153][LE] = 159;
	actionTable[153][LV] = 89;
	actionTable[153][TRU] = 96;
	actionTable[153][FALS] = 97;
	actionTable[153][CH] = 98;
	actionTable[153][ST] = 99;
	actionTable[153][NU] = 100;
	actionTable[153][IDU] = 93;

	//State: 154
	actionTable[154][TYPE] = -25;
	actionTable[154][LEFT_BRACES] = -25;
	actionTable[154][RIGHT_BRACES] = -25;
	actionTable[154][FUNCTION] = -25;
	actionTable[154][VAR] = -25;
	actionTable[154][IF] = -25;
	actionTable[154][ELSE] = -25;
	actionTable[154][WHILE] = -25;
	actionTable[154][DO] = -25;
	actionTable[154][BREAK] = -25;
	actionTable[154][CONTINUE] = -25;
	actionTable[154][RETURN] = -25;
	actionTable[154][ID] = -25;
	actionTable[154][ENDFILE] = -25;

	//State: 155
	actionTable[155][LEFT_BRACES] = -81;
	actionTable[155][IF] = 63;
	actionTable[155][WHILE] = 64;
	actionTable[155][DO] = 65;
	actionTable[155][BREAK] = 68;
	actionTable[155][CONTINUE] = 69;
	actionTable[155][RETURN] = 70;
	actionTable[155][ID] = 22;
	actionTable[155][S] = 161;
	actionTable[155][LV] = 67;
	actionTable[155][IDU] = 71;
	actionTable[155][NB] = 66;

	//State: 156
	actionTable[156][LEFT_BRACES] = -87;
	actionTable[156][RIGHT_BRACES] = -87;
	actionTable[156][IF] = -87;
	actionTable[156][ELSE] = -87;
	actionTable[156][WHILE] = -87;
	actionTable[156][DO] = -87;
	actionTable[156][BREAK] = -87;
	actionTable[156][CONTINUE] = -87;
	actionTable[156][RETURN] = -87;
	actionTable[156][ID] = -87;
	actionTable[156][MT] = 162;

	//State: 157
	actionTable[157][LEFT_PARENTHESIS] = 92;
	actionTable[157][MINUS] = 94;
	actionTable[157][PLUS_PLUS] = 90;
	actionTable[157][MINUS_MINUS] = 91;
	actionTable[157][NOT] = 95;
	actionTable[157][TRUE] = 101;
	actionTable[157][FALSE] = 102;
	actionTable[157][CHARACTER] = 103;
	actionTable[157][STRINGVAL] = 104;
	actionTable[157][NUMERAL] = 31;
	actionTable[157][ID] = 22;
	actionTable[157][E] = 163;
	actionTable[157][L] = 85;
	actionTable[157][R] = 86;
	actionTable[157][Y] = 87;
	actionTable[157][F] = 88;
	actionTable[157][LV] = 89;
	actionTable[157][TRU] = 96;
	actionTable[157][FALS] = 97;
	actionTable[157][CH] = 98;
	actionTable[157][ST] = 99;
	actionTable[157][NU] = 100;
	actionTable[157][IDU] = 93;

	//State: 158
	actionTable[158][LEFT_BRACES] = -33;
	actionTable[158][RIGHT_BRACES] = -33;
	actionTable[158][IF] = -33;
	actionTable[158][ELSE] = -33;
	actionTable[158][WHILE] = -33;
	actionTable[158][DO] = -33;
	actionTable[158][BREAK] = -33;
	actionTable[158][CONTINUE] = -33;
	actionTable[158][RETURN] = -33;
	actionTable[158][ID] = -33;

	//State: 159
	actionTable[159][RIGHT_PARENTHESIS] = 164;
	actionTable[159][COMMA] = 165;

	//State: 160
	actionTable[160][RIGHT_PARENTHESIS] = -68;
	actionTable[160][COMMA] = -68;
	actionTable[160][AND] = 114;
	actionTable[160][OR] = 115;

	//State: 161
	actionTable[161][LEFT_BRACES] = -28;
	actionTable[161][RIGHT_BRACES] = -28;
	actionTable[161][IF] = -28;
	actionTable[161][ELSE] = -28;
	actionTable[161][WHILE] = -28;
	actionTable[161][DO] = -28;
	actionTable[161][BREAK] = -28;
	actionTable[161][CONTINUE] = -28;
	actionTable[161][RETURN] = -28;
	actionTable[161][ID] = -28;

	//State: 162
	actionTable[162][LEFT_BRACES] = -81;
	actionTable[162][IF] = 63;
	actionTable[162][WHILE] = 64;
	actionTable[162][DO] = 65;
	actionTable[162][BREAK] = 68;
	actionTable[162][CONTINUE] = 69;
	actionTable[162][RETURN] = 70;
	actionTable[162][ID] = 22;
	actionTable[162][S] = 167;
	actionTable[162][LV] = 67;
	actionTable[162][IDU] = 71;
	actionTable[162][NB] = 66;

	//State: 163
	actionTable[163][RIGHT_PARENTHESIS] = 168;
	actionTable[163][AND] = 114;
	actionTable[163][OR] = 115;

	//State: 164
	actionTable[164][RIGHT_SQUARE] = -59;
	actionTable[164][SEMI_COLON] = -59;
	actionTable[164][RIGHT_PARENTHESIS] = -59;
	actionTable[164][COMMA] = -59;
	actionTable[164][AND] = -59;
	actionTable[164][OR] = -59;
	actionTable[164][LESS_THAN] = -59;
	actionTable[164][GREATER_THAN] = -59;
	actionTable[164][LESS_OR_EQUAL] = -59;
	actionTable[164][GREATER_OR_EQUAL] = -59;
	actionTable[164][EQUAL_EQUAL] = -59;
	actionTable[164][NOT_EQUAL] = -59;
	actionTable[164][PLUS] = -59;
	actionTable[164][MINUS] = -59;
	actionTable[164][TIMES] = -59;
	actionTable[164][DIVIDE] = -59;

	//State: 165
	actionTable[165][LEFT_PARENTHESIS] = 92;
	actionTable[165][MINUS] = 94;
	actionTable[165][PLUS_PLUS] = 90;
	actionTable[165][MINUS_MINUS] = 91;
	actionTable[165][NOT] = 95;
	actionTable[165][TRUE] = 101;
	actionTable[165][FALSE] = 102;
	actionTable[165][CHARACTER] = 103;
	actionTable[165][STRINGVAL] = 104;
	actionTable[165][NUMERAL] = 31;
	actionTable[165][ID] = 22;
	actionTable[165][E] = 169;
	actionTable[165][L] = 85;
	actionTable[165][R] = 86;
	actionTable[165][Y] = 87;
	actionTable[165][F] = 88;
	actionTable[165][LV] = 89;
	actionTable[165][TRU] = 96;
	actionTable[165][FALS] = 97;
	actionTable[165][CH] = 98;
	actionTable[165][ST] = 99;
	actionTable[165][NU] = 100;
	actionTable[165][IDU] = 93;

	//State: 166
	actionTable[166][LEFT_BRACES] = -84;
	actionTable[166][RIGHT_BRACES] = -84;
	actionTable[166][IF] = -84;
	actionTable[166][ELSE] = -84;
	actionTable[166][WHILE] = -84;
	actionTable[166][DO] = -84;
	actionTable[166][BREAK] = -84;
	actionTable[166][CONTINUE] = -84;
	actionTable[166][RETURN] = -84;
	actionTable[166][ID] = -84;
	actionTable[166][ME] = 170;

	//State: 167
	actionTable[167][LEFT_BRACES] = -30;
	actionTable[167][RIGHT_BRACES] = -30;
	actionTable[167][IF] = -30;
	actionTable[167][ELSE] = -30;
	actionTable[167][WHILE] = -30;
	actionTable[167][DO] = -30;
	actionTable[167][BREAK] = -30;
	actionTable[167][CONTINUE] = -30;
	actionTable[167][RETURN] = -30;
	actionTable[167][ID] = -30;

	//State: 168
	actionTable[168][SEMI_COLON] = 171;

	//State: 169
	actionTable[169][RIGHT_PARENTHESIS] = -67;
	actionTable[169][COMMA] = -67;
	actionTable[169][AND] = 114;
	actionTable[169][OR] = 115;

	//State: 170
	actionTable[170][LEFT_BRACES] = -81;
	actionTable[170][IF] = 63;
	actionTable[170][WHILE] = 64;
	actionTable[170][DO] = 65;
	actionTable[170][BREAK] = 68;
	actionTable[170][CONTINUE] = 69;
	actionTable[170][RETURN] = 70;
	actionTable[170][ID] = 22;
	actionTable[170][S] = 172;
	actionTable[170][LV] = 67;
	actionTable[170][IDU] = 71;
	actionTable[170][NB] = 66;

	//State: 171
	actionTable[171][LEFT_BRACES] = -31;
	actionTable[171][RIGHT_BRACES] = -31;
	actionTable[171][IF] = -31;
	actionTable[171][ELSE] = -31;
	actionTable[171][WHILE] = -31;
	actionTable[171][DO] = -31;
	actionTable[171][BREAK] = -31;
	actionTable[171][CONTINUE] = -31;
	actionTable[171][RETURN] = -31;
	actionTable[171][ID] = -31;

	//State: 172
	actionTable[172][LEFT_BRACES] = -29;
	actionTable[172][RIGHT_BRACES] = -29;
	actionTable[172][IF] = -29;
	actionTable[172][ELSE] = -29;
	actionTable[172][WHILE] = -29;
	actionTable[172][DO] = -29;
	actionTable[172][BREAK] = -29;
	actionTable[172][CONTINUE] = -29;
	actionTable[172][RETURN] = -29;
	actionTable[172][ID] = -29;

}


void getToken(int &token, int &tokenSecundario){
	token_struct t;
	t = nextToken();
	token = t.token;
	if (t.tokenSecundario != -1){
		tokenSecundario = t.tokenSecundario;
	}
}

void parse(){
	int q = 0, token;
	static int tokenSecundario = -1;
	initializeReservedWordMap();
	build_rule_vector();
	build_action_table();
	states.push(q);
	getToken(token,tokenSecundario);
	do{
		//cout << "[!] Current State : "  << q << " - Token: " << t_terminalNames[token_id] << " - On Table : " << actionTable[q][token_id] << endl;;
			if(actionTable[q].count(token) < 1){
					errorRoutines::throwSyntaxError();
			}
			else{
					int p = actionTable[q][token];
					if(IS_SHIFT(p)){
							states.push(p);
							getToken(token,tokenSecundario);
					}
					else if(IS_REDUCTION(p)){
							int r = RULE(p);
							for(int i = 0;i<vec_rules[r].second;i++){
									states.pop();
							}
							states.push(actionTable[states.top()][vec_rules[r].first]);
							//semantics(r,tokenSecundario);
					}
					else{
							errorRoutines::throwSyntaxError();
					}
					q = states.top();
			}
	} while(q != ACC);

	if (errorRoutines::hasError){
		cout << "[-] Parsing errors detected!" << endl;
	}
	else{
		cout << "[+] No parsing errors detected!" << endl;

	}
}
